### ISSUE TITLE
Causes the server from completely closing when running /stop.

### ISSUE THREAD

**Issue by frikinjay** [ExcessiveAmountsOfZombies/EightsEconomyP#1]
There isnt anything to show other than it doesnt happen with the 1.0.1 version of the mod not present.

**Comment by ExcessiveAmountsOfZombies** [comment]
Could you give me a bit of a rundown of what you were doing prior to running /stop? I can't replicate it currently and remember fixing this before releasing 1.0.0

**Comment by frikinjay** [comment]
The server was running as usual nothing out of the ordinary. This happened everytime i tried to stop the server and had to force close it every time.

**Comment by ExcessiveAmountsOfZombies** [comment]
Maybe a bit of a longshot, but could you redownload 1.0.1 and put it on the server?

**Comment by MrRubberDucky** [comment]
I can confirm that the same happens to me, both on a freshly installed server (locally) and on a server that I manage.
(yes, I tried the 1.0.1 version)

I found it rather easy to reproduce on a clean instance with Shoppy, OctoEconomyApi and EightsEconomyP.
Join world, set your balance to example 1k (or maybe just use any commands? didn't test it that much) and stop the server. Server won't close completely anymore and will require manual killing by either server software or manually.

**Comment by ExcessiveAmountsOfZombies** [comment]
@MrRubberDucky do you have luckperms installed on the server too?
Edit: @frikinjay you too

**Comment by frikinjay** [comment]
I do not have luckperms installed.

**Comment by MrRubberDucky** [comment]
> @MrRubberDucky do you have luckperms installed on the server too? Edit: @frikinjay you too

I do on the server I manage but I tried on a clean instance without luckperms and it had same symptoms. (edit note: screwed up quote)

**Comment by ExcessiveAmountsOfZombies** [comment]
Could you give me a thread dump from while the server is refusing to fully shut down?
https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/tooldescr016.html

You'll have to find the pid (either windows or linux not sure what you guys are running the server on)

jstack [pid] > pathofdump.txt 

and then upload it to hastebin or something

**Comment by MrRubberDucky** [comment]
> Could you give me a thread dump from while the server is refusing to fully shut down? https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/tooldescr016.html
> 
> You'll have to find the pid (either windows or linux not sure what you guys are running the server on)
> 
> jstack [pid] > pathofdump.txt
> 
> and then upload it to hastebin or something

Well I couldn't do the fancy magic on the server since I don't have access to ssh but I worked around by throwing the server files onto my pc and hosting it locally so here it is (also it has luckperms on it)
https://www.toptal.com/developers/hastebin/eqecovapow.pl

Clean instance, though this one tends to only do this when you do /balance set <player> <amount> and then /stop the server after 5-10s https://www.toptal.com/developers/hastebin/fanukuxima.pl

**Comment by ExcessiveAmountsOfZombies** [comment]
I don't mean to be a pain when I say this, but I can't replicate the scenario when I don't have luckperms installed and even then both of these hastebins don't seem to indicate that any of my code is holding the server hostage.

**Comment by frikinjay** [comment]
I've had the mod disabled for a while now and the server has been shutting down fine without it.

**Comment by ExcessiveAmountsOfZombies** [comment]
Not sure if you two care anymore, but I gave it some thought and if it's my thread usage keeping the server from closing I can add a config option that lets you save on the main thread. As a result I will also only save when the player needs it.
https://www.curseforge.com/minecraft/mc-mods/eightseconomyp/files/3771254
