### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Balakay420** [ExcessiveAmountsOfZombies/EightsEconomyP#2]
[Crash log.txt](https://github.com/ExcessiveAmountsOfZombies/EightsEconomyP/files/8935177/Crash.log.txt)
I get this crash when starting server

**Comment by Balakay420** [comment]
Seems to be a conflict with bclib

**Comment by ExcessiveAmountsOfZombies** [comment]
update to 1.0.4 and see if that fixes it

**Comment by Balakay420** [comment]
I'm using 1.18.2
