### ISSUE TITLE
eights_economy_p requires octo_economy_api 1.1.0

### ISSUE THREAD

**Issue by alexlarraga1** [ExcessiveAmountsOfZombies/EightsEconomyP#3]
Mod curseforge version: 1.1.0-all

Mod version in FML: 1.0.4

Temporary solution: Downgrade to 1.0.4

[crash.txt](https://github.com/ExcessiveAmountsOfZombies/EightsEconomyP/files/9647817/crash.txt)

**Comment by ExcessiveAmountsOfZombies** [comment]
uploading a new version with a fix
