### ISSUE TITLE
Server Crashing on Player Load

### ISSUE THREAD

**Issue by sjstark** [ExcessiveAmountsOfZombies/EightsEconomyP#4]
**Platform:** Forge
**Minecraft Version:** 1.19.2
**Mod Version:** 1.1.0

**What Happened:** 
I unfortunately really don't have too much information to provide. I started running a Valhelsia 5 server, which includes this mod. A user reported a server crash but didn't recall what he was doing when it crashed. The server restarts fine, but when this same user tries to reconnect the server crashes again. [I originally reported it to the Val5 discord](https://discord.com/channels/396333981601234944/553936304040050689/1127743817177645146) and [they suggested reaching out to your discord](https://discord.com/channels/396333981601234944/553936304040050689/1127806841510973530) since the logs mention the economy mod.
The server works fine when any other user tries to connect, so I think it's something isolated to the chunk that the original player crashed the server.

I know this is may not be too helpful without what specifically was happening with the player 😕.. 

**Relevant Logs:** https://gist.github.com/sjstark/840023d3c537214fd80d901e2e604770

**Additional Info:** Using the [Valhelsia 5.1.0](https://www.curseforge.com/minecraft/modpacks/valhelsia-5) modpack

**Comment by sjstark** [comment]
Seeing now that there's a 1.1.1 version, can definitely try updating to that if we think that has a change that may hit on this type of error? It's just a bit of a pain to get the update distributed to everyone on the server

**Comment by ExcessiveAmountsOfZombies** [comment]
EightsEconomyP is a serverside mod, you won't need to get other players to download it
